version = 2
[grpc]
  address = "/run/containerd/containerd.sock"
  tcp_address = "0.0.0.0:8080"
  uid = 0
  gid = 0
# Enable stargz snapshotter
[proxy_plugins]
  [proxy_plugins.stargz]
    type = "snapshot"
    address = "/run/containerd-stargz-grpc/containerd-stargz-grpc.sock"