---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Dev dashboard"
subtitle: "Takaro"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#be81f6"
    highlight-secondary: "#664DE5"
    highlight-hover: "#a56ed8"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#363636"
    link-hover: "#664DE5"
  dark:
    highlight-primary: "#be81f6"
    highlight-secondary: "#664DE5"
    highlight-hover: "#a56ed8"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#f5f5f5"
    link-hover: "#664DE5"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Takaro development"
  icon: "fa fa-grin"
  content: "This is a development dashboard for Takaro. Logins for the development tools default to takaro/takaro."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/niekcandaele/takaro"
    target: "_blank" # optional html a tag target attribute
  - name: "Docs"
    icon: "fab fa-book"
    url: "https://docs.takaro.io"
    target: "_blank" # optional html a tag target attribute
#  - name: "Wiki"
#    icon: "fas fa-book"
#    url: "https://www.wikipedia.org/"
# this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
# see url field and assets/additional-page.yml.dist used in this example:
#- name: "another page!"
#  icon: "fas fa-file-alt"
#  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Backend"
    icon: "fas fa-cloud"
    items:
      - name: "API"
        icon: "fas fa-cog"
        subtitle: "Main Takaro API"
        url: "http://localhost:13000/api.html"
        target: "_blank"
      - name: "app-agent"
        icon: "fas fa-cog"
        subtitle: "Manages Firecracker and executes Functions"
        url: "http://localhost:13004/api.html"
        target: "_blank"
  - name: "Frontend"
    icon: "fas fa-cloud"
    items:
      - name: "Main app"
        icon: "fas fa-desktop"
        subtitle: "Main Takaro app"
        url: "http://localhost:13001"
        target: "_blank"
      - name: "Storybook"
        icon: "fas fa-book-open"
        subtitle: "Storybook component development"
        url: "http://localhost:13002"
        target: "_blank"
  - name: "Dev tools"
    icon: "fas fa-cloud"
    items:
      - name: "pgadmin"
        icon: "fas fa-database"
        subtitle: "Database UI for PostgreSQL"
        url: "http://localhost:5050"
        target: "_blank"
      - name: "Bull dashboard"
        icon: "fas fa-chart-line"
        subtitle: "Bull queues dashboard"
        url: "http://localhost:13004/queues"
        target: "_blank"
      - name: "Prometheus"
        icon: "fas fa-chart-line"
        subtitle: "Prometheus metrics"
        url: "http://localhost:13006"
        target: "_blank"
      - name: "Grafana"
        icon: "fas fa-chart-bar"
        subtitle: "Dashboards!"
        url: "http://localhost:13007"
        target: "_blank"
