version: v0.11.0

dsn: postgres

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1:13001
        - http://127.0.0.1:13002
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
        - X-TAKARO
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://127.0.0.1:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:13001/login
  allowed_return_urls:
    - http://127.0.0.1:13001/login
    - http://127.0.0.1:13001/settings
    - http://127.0.0.1:13001/settings/discord
    - http://127.0.0.1:13001/settings/steam
    - http://127.0.0.1:13001/profile
    - http://127.0.0.1:13001/

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: false
    lookup_secret:
      enabled: false
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: discord
            provider: discord
            client_id: "placeholder"
            client_secret: "placeholder"
            mapper_url: file:///etc/config/kratos/discord.jsonnet
            scope:
              - identify
              - email
          - id: steam
            provider: generic
            client_id: "placeholder"
            client_secret: "placeholder"
            mapper_url: file:///etc/config/kratos/steam.jsonnet
            issuer_url: "http://steam-auth-proxy:19000"
            auth_url: "http://localhost:19000/authorize"
            token_url: "http://steam-auth-proxy:19000/token"
            scope:
              - openid

  flows:
    error:
      ui_url: http://127.0.0.1:13001/error

    settings:
      ui_url: http://127.0.0.1:13001/profile
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:13001/account/recovery
      use: code

    verification:
      enabled: false
      ui_url: http://127.0.0.1:13001/account/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:13001/dashboard

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:13001/logout-return

    login:
      ui_url: http://127.0.0.1:13001/login
      lifespan: 10m
      after:
        default_browser_return_url: http://127.0.0.1:13001/

    registration:
      enabled: true
      lifespan: 10m
      ui_url: http://127.0.0.1:13001/registration
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: false

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: user_v0
  schemas:
    - id: user_v0
      url: file:///etc/config/kratos/user.schema.json

courier:
  smtp:
    connection_uri: 'smtp://mailhog:1025/?disable_starttls=true'
    from_address: noreply@takaro.io
    from_name: Takaro
# courier:
#   delivery_strategy: http
#   http:
#     request_config:
#       #url: https://api.postmarkapp.com/email
#       url: http://192.168.50.35:9999
#       method: POST
#       body: file:///etc/config/kratos/default.template.jsonnet
#       headers:
#         Content-Type: application/json
#         Accept: application/json
#       auth:
#         type: api_key
#         config:
#           name: X-Postmark-Server-Token
#           value: xxx
#           in: header

# https://github.com/ory/kratos/pull/3624
# SPA flows no longer return a 422 error.
feature_flags:
  use_continue_with_transitions: true
