/* eslint-disable quotes */
// Static content arrays for event generation
// Separated for better maintainability and potential localization support

export const CHAT_MESSAGES = [
  // Very short (1-3 words)
  'gg',
  'lol',
  'brb',
  'help!',
  'nice!',
  'oof',
  'anyone?',
  'hey',
  'sup',
  'thx',
  'np',
  'omg',
  'wow',
  'rip',
  'f',
  'same',
  'agreed',
  'nope',
  'yes!',
  'nooo',
  'afk',
  'back',
  'lag?',

  // Simple commands (no parameters)
  '/ping',
  '/help',
  '/balance',
  '/topcurrency',
  '/tplist',
  '/viewtickets',
  '/nextdraw',
  '/daily',
  '/streak',
  '/topstreak',
  '/gimme',
  '/claim',
  '/confirmtransfer',

  // Common command typos
  '/balacne',
  '/trnasfer',
  '/hlep',
  '/dayli',
  '/gime',

  // Partial commands
  '/tp',
  '/tra',
  '/sho',
  '/buy',

  // Teleport commands with common location names
  '/tp home',
  '/tp base',
  '/tp spawn',
  '/tp farm',
  '/tp mine',
  '/tp shop',
  '/tp friend',
  '/settp home',
  '/settp base',
  '/settp farm',
  '/settp mine',
  '/settp secret',
  '/deletetp old',
  '/deletetp temp',
  '/setpublic spawn',
  '/setpublic shop',
  '/setprivate base',
  '/setprivate home',

  // Economy commands with realistic amounts
  '/transfer bob 50',
  '/transfer alice 100',
  '/transfer friend 25',
  '/transfer teammate 500',
  '/transfer newbie 10',
  '/grantcurrency newplayer 1000',
  '/revokecurrency hacker 99999',

  // Shop commands
  '/shop',
  '/shop 1',
  '/shop 2',
  '/shop 1 3',
  '/shop 1 3 buy',
  '/shop 2 1 buy',

  // Lottery commands
  '/buyticket 1',
  '/buyticket 5',
  '/buyticket 10',

  // Short (4-7 words)
  'Hello everyone!',
  'Anyone want to team up?',
  'Where is everyone?',
  'Anyone need help?',
  'Great game so far',
  'Found some good loot',
  'Heading to the base',
  'This area looks dangerous',
  'Nice weather today',
  'Anyone seen any zombies?',
  'I need some resources',
  'Thanks for the help!',
  'Need some food badly',
  'This place is creepy',
  'Found a good spot',
  'Trading iron for diamonds',
  'Zombies everywhere help me',
  'Just died again fml',
  'Anyone have spare ammo?',
  'Where did you go?',
  'On my way now',
  'Be there in 5',
  'Watch out behind you!',
  'I hear them coming',

  // Medium (8-15 words)
  'Just found an awesome base location near the river, anyone want to join?',
  'Does anyone know where I can find more ammunition around here?',
  'I think there might be a horde coming from the north side',
  'Been working on my base all day and finally got the walls up',
  'The trader has some really good deals today, you should check it out',
  'Why do I always run out of food at the worst possible times?',
  'This new update is amazing, the graphics look so much better now',
  'Just cleared out a whole building, so much loot inside!',
  'Anyone else having connection issues or is it just me?',
  'Found a secret bunker at coordinates 250, -150, tons of military gear',
  'My base got raided while I was offline, lost everything',
  'Finally crafted my first motorcycle, this changes everything!',

  // Long (15+ words)
  'So I was exploring the abandoned city and found this huge stash of weapons in a police station, but there were like 20 zombies guarding it',
  "Anyone else having trouble with the new zombie AI? They seem way smarter now and keep finding ways into my base through gaps I didn't even know existed",
  "I've been playing for 3 hours straight and still haven't found any diamonds... am I looking in the wrong places or just unlucky?",
  "Hey everyone, I'm setting up a trading post at coordinates 150, -200. I'll trade food for building materials. Also looking for someone to help defend it at night",
  'Just had the most intense fight ever - three zombie dogs, two cops, and a bunch of regular zombies all at once. Barely survived with 5 health',
  "Has anyone figured out the best way to farm yet? I'm trying to set up a sustainable food source but the crops keep dying",
  'The blood moon last night was insane! My entire east wall got destroyed and I had to rebuild everything from scratch this morning',
  "I found this amazing cave system that goes super deep underground. There's iron everywhere but also lots of zombies. Anyone brave enough to explore it with me?",

  // Very long story-like messages
  'Okay so funny story: I was sneaking through a house looking for loot when I accidentally triggered an alarm. Next thing I know, the entire neighborhood of zombies is chasing me. I ran for like 10 minutes straight and ended up jumping off a cliff into water. Lost half my health but survived!',
  "PSA: Don't go near the military base at night. I repeat, DO NOT GO NEAR THE MILITARY BASE AT NIGHT. Just lost all my best gear trying to loot it. There must be 50+ zombies there and they respawn super fast",
  "Just wanted to share my base design strategy: I dig a deep moat around the entire perimeter, fill it with spikes, then build bridges that I can destroy during blood moons. It's worked perfectly for the last 3 attacks. Happy to help anyone set up something similar",
  "So I've been experimenting with different base locations and I think I found the perfect spot: it's on top of a hill with natural cliffs on three sides, near water, close to a town for looting, but far enough away that zombies don't randomly spawn. Coordinates are 700, 450 if anyone wants to be neighbors",

  // Questions of varying length
  'how?',
  'where?',
  'really?',
  'anyone online?',
  "what's the best weapon?",
  'how do I craft antibiotics?',
  'where do I find oil?',
  'what level are you?',
  'has anyone found the trader yet this week?',
  "what's the best way to deal with zombie dogs? they keep killing me",
  'is it just me or did they make nights darker in the last update? I can barely see anything without a torch now',
  "does anyone know if there's a limit to how many vehicles you can have? I want to start a collection",
  "what's better for base defense: wood spikes or barbed wire? I can't decide",

  // Reactions and contextual responses
  "that's rough",
  'I feel your pain',
  'happens to me all the time',
  'you should try going underground, much safer',
  'nah the military base is easy if you have good gear',
  'I can help with that, give me 5 minutes to get there',
  'try using a sledgehammer, works every time',
  "you need to cook it first or you'll get sick",
  'the desert biome has tons of oil',
  "zombies can't swim, use that to your advantage",
  'always carry bandages, trust me on this',

  // Random observations and comments
  'this game is so addictive',
  'I should probably go to sleep soon',
  "one more hour then I'm done",
  'why is it always raining when I need to travel',
  'these graphics are incredible',
  'the sound design in this game is terrifying',
  'I love the base building mechanics',
  'inventory management is my biggest enemy',
  'I spend more time organizing than playing',
  'just found my first helicopter crash!',
  "is that a bear? OH NO IT'S A BEAR",
  'accidentally ate raw meat again...',
  'my stamina bar is broken I swear',
  'how do people build such amazing bases',
  "I'm basically a hoarder at this point",
  'do vehicles despawn if you leave them?',
  "my character hasn't slept in 3 days lol",

  // Complaints and frustrations
  'this is bs',
  'I hate vultures so much',
  'lost all my stuff AGAIN',
  'why do I even try',
  'rage quit incoming',
  'this game hates me',
  'zombies are too OP',
  'nerf the dogs please',
  'fix the spawning already',
  'another crash great',
  'there goes 2 hours of progress',
  'why did I click that',
  "I'm uninstalling",
  "jk I'm addicted",
  "can't quit now",

  // Helpful tips and advice
  'pro tip: crouch to avoid mines',
  'honey is the best healing item',
  'always have an escape route planned',
  'two exits minimum for any base',
  'dig straight down for easy stone',
  'snow biome = infinite water',
  'cactus gives you water in desert',
  "zombies can't break steel blocks",
  'put your forge underground',
  'birds mean a horde is coming',
  'red sky at night, zombies delight',
  'green repair kits are gold',
  'level 5 tools are worth it',
  'spec into one weapon type first',
  'stamina > health early game',

  // Additional chat messages
  'The base is coming along nicely, just need more steel for the walls',
  'perfect timing!',
  'give me a minute to sort my inventory',
  'does anyone have a spare pickaxe?',
  "I'll trade you 10 iron for that",
  'the horde night is coming, everyone prepare!',
  'check out my new ride',
  'finally found a working 4x4',
  'got raided last night, they took everything',
  'who wants to do a supply run?',
  'meet me at the trader for some good deals',
  'just crafted tier 6 armor, feeling invincible',

  // Event-specific messages
  'killed another zombie, when will they stop coming?',
  'picked up some ammo, finally!',
  "dropped my best weapon by accident, don't let it despawn!",
  'connected to defend the base',
  'heading out for a bit, hold down the fort',
  'nice shot!',
  'that was close',
  'behind you!',
  'thanks for the backup',
  'no problem, anytime',
  "let's team up for the blood moon",
  'I have extra food if anyone needs',
  'running low on meds',
  'found a secret stash in the basement',
  'this fog is so thick I can barely see',
  'watch out for the landmines near the military base',
  "don't go in there, it's a trap!",
  'following the road north to find a new base location',
  'just saw 3 screamers, get ready for a wave',
  'my motorcycle just ran out of gas in the worst spot',
  'anyone know a good seed for lots of cities?',
  'the new POIs in this update are amazing',
  'finally reached gamestage 100!',
  'why is it always raining when I need to build?',
  'found the super corn recipe, game changer',
  'electric fence is up and running',
  'auger is broken again, this thing eats repair kits',
  'just fell through the world, lost everything',
  'server lag is killing me',
  'when is the next wipe?',
  'anyone want to start fresh on a new map?',
  'looking for people to join our community base',
  'selling steel for dukes, best prices around',
  'buying brass in bulk',
  'need help clearing a tier 5 POI',
  "trader isn't spawning for me, anyone else having this issue?",
];

export const WEAPONS = [
  'sword',
  'bow',
  'rifle',
  'pistol',
  'axe',
  'spear',
  'crossbow',
  'knife',
  'club',
  'hammer',
  'mace',
  'dagger',
  'shotgun',
  'sniper',
  'machete',
  'staff',
];

export const ACTIONS = ['picked up', 'dropped'];
