import {
  ThemeName,
  ThemeType,
  darkTheme as darkThemeWithPrefix,
  lightTheme as LightThemeWithPrefix,
} from '@takaro/lib-components';
import type { editor } from 'monaco-editor';

const darkTheme = stripHashFromTheme(darkThemeWithPrefix);
const lightTheme = stripHashFromTheme(LightThemeWithPrefix);

function stripHashFromTheme(theme: ThemeType): ThemeType {
  const t: Record<string, string> = {};
  for (const [key, value] of Object.entries(theme.colors)) {
    t[key] = value.substring(1);
  }
  return theme;
}

export function getMonacoTheme(themeName: ThemeName): editor.IStandaloneThemeData {
  const themes: Record<string, editor.IStandaloneThemeData> = {
    'takaro-dark': takaroDarkTheme,
    'takaro-light': takaroLightTheme,
  };

  return themes[`takaro-${themeName}`];
}

export const takaroLightTheme: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,

  colors: {
    background: darkTheme.colors.background,
    foreground: darkTheme.colors.text,
    // focusBorder: 'AD9CFF',
    'selection.background': darkTheme.colors.primary,
    'selection.foreground': darkTheme.colors.text,

    // 'scrollbar.shadow': '0000007e',
    // 'input.background': '0F0E0E',
    // 'input.foreground': '999',
    // 'button.background': 'edffa5',
    // 'button.foreground': '151515',
    // 'button.hoverBackground': 'dcff50',
    // 'textLink.foreground': 'e5e5e5',
    // 'button.secondaryForeground': 'c5c5c5',
    // 'button.secondaryBacground': '2a2a2a',
    // 'button.secondaryHoverBackground': '373737',
    //
    // 'activityBar.foreground': 'dedede',
    // 'activityBar.background': '000',
    // 'activityBar.inactiveForeground': '999',
    // 'activityBarBadge.foreground': '000',
    // 'activityBarBadge.background': 'edffa5',
    // 'activityBar.border': '000',
    // 'actibityBar.activeBackground': '151515',
    //
    // 'sideBar.background': '000',
    // 'sideBar.foreground': '999',
    // 'sideBarSectionHeader.background': '151515',
    // 'sideBarSectionHeader.border': '00000000',
    // 'sideBarSectionHeader.foreground': 'e5e5e5',
    // 'sideBarTitle.foreground': 'e5e5e5',
    // 'sideBar.border': '00000000',
    // 'list.dropBackground': '151515',
    // 'list.focusForeground': '808080',
    // 'list.focusBackground': 'e5e5e51a',
    // 'list.highlightForeground': 'e5e5e5',
    'list.activeSelectionBackground': darkTheme.colors.backgroundAlt,
    'list.activeSelectionForeground': darkTheme.colors.text,
    //
    // 'statusBar.background': '000',
    // 'statusBar.foreground': '808080',
    // 'statusBar.border': '00000000',
    // 'statusBar.debuggingBackground': '563300',
    // 'statusBar.debuggingForeground': '999',
    // 'statusBar.noFolderBackground': '5d3fe0',
    // 'statusBar.noFolderForeground': 'e5e5e5',
    // 'statusBarItem.remoteBackground': 'cef144',
    // 'statusBarItem.remoteForeground': '151515',
    //
    // 'tab.activeBackground': '151515',
    // 'tab.activeForeground': 'e5e5e5',
    // 'tab.inactiveBackground': '000',
    // 'tab.inactiveForeground': '999',
    // 'tab.hoverBackground': 'E5E5E51A',
    // 'tab.border': '151515',
    //
    // 'titleBar.activeBackground': '000',
    // 'titleBar.activeForeground': '808080',
    // 'titleBar.border': '00000000',
    // 'titleBar.inactiveBackground': '000',
    //
    'menu.foreground': darkTheme.colors.text,
    'menu.background': darkTheme.colors.backgroundAlt,
    // 'menubar.selectionForeground': 'c5c5c5',
    // 'menubar.selectionBackground': 'e5e5e51a',
    'menu.selectionForeground': darkTheme.colors.text,
    'menu.selectionBackground': darkTheme.colors.backgroundAlt,
    'menu.selectionBorder': darkTheme.colors.primary,
    'menu.border': darkTheme.colors.backgroundAccent,
    //
    'editor.background': darkTheme.colors.background,
    // 'editorLineNumber.foreground': '858585',
    // 'editorLineNumber.activeForeground': 'c6c6c6',
    //
    'editor.lineHighlightBackground': darkTheme.colors.backgroundAlt,
    'editor.lineHighlightBorder': darkTheme.colors.backgroundAlt,
    //
    // 'breadcrumb.background': '151515',
    // 'breadcrumb.foreground': '999',
    // 'breadcrumb.focusForeground': 'e5e5e5',
    // 'editorGroupHeader.border': '00000000',
    // 'editorGroupHeader.tabsBackground': '000',
    //
    // 'scrollbarSlider.background': '79797966',
    // 'scrollbarSlider.hoverBackground': '646464b3',
    // 'scrollbarSlider.activeBackground': 'bfbfbf66',
    //
    // 'widget.shadow': '0000005c',
    'editorWidget.foreground': darkTheme.colors.text,
    'editorWidget.background': darkTheme.colors.backgroundAlt,
    'editorWidget.border': darkTheme.colors.backgroundAccent,

    'editor.selectionBackground': darkTheme.colors.primary,
    'editor.selectionForeground': darkTheme.colors.text,

    // 'pickerGroup.border': '3f3f46',
    // 'pickerGroup.foreground': '3794ff',
    // 'editorWidget.resizeBorder': '5f5f5f',
    // 'debugToolBar.background': '333',
    // 'debugToolBar.border': '474747',
    //
    // errorForeground: 'f48771',
    // warningForeground: 'F7CC66',
    // 'editorError.foreground': 'f48771',
    // 'list.errorForeground': 'f48771',
    // 'list.warningForeground': 'F7CC66',
    // 'editorWarning.foreground': 'F7CC66',
    //
    // 'gitDecoration.deletedResourceForeground': 'C54444',
    // 'gitDecoration.untrackedResourceForeground': '9FE7A0',
    // 'gitDecoration.conflictingResourceForeground': 'ED6C6C',
    // 'gitDecoration.ignoredResourceForeground': '585858',
    // 'gitDecoration.modifiedResourceForeground': 'DD763C',
  },

  rules: [
    { token: 'string', foreground: 'BFD084' },
    {
      token: 'punctuation.definition.string',
      foreground: lightTheme.colors.primary,
    },
    {
      token: 'constant.character.escape',
      foreground: lightTheme.colors.primary,
    },
    {
      token: 'text.html constant.character.entity.named',
      foreground: lightTheme.colors.primary,
    },
    { token: 'text.html.derivative', foreground: 'E5E5E5' },
    {
      token: 'punctuation.definition.entity.html',
      foreground: lightTheme.colors.primary,
    },
    { token: 'template.expression.begin', foreground: '7AD9FB' },
    { token: 'template.expression.end', foreground: '7AD9FB' },
    {
      token: 'punctuation.definition.template-expression.begin',
      foreground: '7AD9FB',
    },
    {
      token: 'punctuation.definition.template-expression.end',
      foreground: '7AD9FB',
    },

    { token: 'variable', foreground: 'ff0000' },
    { token: 'variable.other', foreground: 'ffffff' },
    { token: 'variable.parameter', foreground: 'ffffff' },
    { token: 'variable.language', foreground: '00ff00' },

    { token: 'constant', foreground: '7AD9FB' },
    { token: 'keyword', foreground: lightTheme.colors.primary },
    { token: 'modifier', foreground: lightTheme.colors.primary },
    { token: 'storage', foreground: lightTheme.colors.primary },
    { token: 'punctuation.definition.block', foreground: '86897A' },
    { token: 'punctuation.definition.parameters', foreground: '86897A' },
    { token: 'punctuation.accessor', foreground: '86897A' },
    { token: 'source.groovy.embedded', foreground: 'E5E5E5' },
    { token: 'comment', foreground: '6f6f6f' },
    { token: 'docblock', foreground: '6f6f6f' },

    { token: 'meta.function-call', foreground: 'CDF861' },
    { token: 'meta.brace.round', foreground: '86897A' },
    { token: 'meta.jsx.children', foreground: 'E5E5E5' },
    { token: 'meta.embedded', foreground: 'E5E5E5' },
    { token: 'meta.template.expression', foreground: 'E5E5E5' },
    { token: 'meta.type.annotation', foreground: lightTheme.colors.primary },
    { token: 'meta.type.annotation entity.name.type', foreground: 'CABEFF' },
    { token: 'meta.definition.variable', foreground: '00ff00' },

    { token: 'entity.name.type.class', foreground: 'ffffff' },
    { token: 'entity.name.type.module', foreground: 'CABEFF' },
    { token: 'entity.name.function', foreground: 'ff0000' },
    { token: 'entity.name.tag.css', foreground: 'CDF861' },
    { token: 'entity.name.section', foreground: 'ffffff' },

    { token: 'entity.other.attribute-name', foreground: 'CDF861' },
    { token: 'entity.other.attribute-name.id', foreground: 'CDF861' },
    { token: 'entity.other.attribute-name.class', foreground: 'CDF861' },
    { token: 'entity.other.inherited-class', foreground: lightTheme.colors.primary },

    { token: 'variable.object.property', foreground: 'ffffff' },
    { token: 'modifier', foreground: lightTheme.colors.primary },
    { token: 'variable.language.this', foreground: lightTheme.colors.primary },
    { token: 'support.type.object', foreground: lightTheme.colors.primary },
    { token: 'support.module', foreground: '7AD9FB', fontStyle: 'italic' },
    { token: 'support.node', foreground: '7AD9FB', fontStyle: 'italic' },
    { token: 'support.type.ts', foreground: '7AD9FB' },
    { token: 'support.function.css', foreground: lightTheme.colors.primary },
    { token: 'support.constant.css', foreground: lightTheme.colors.primary },
    { token: 'keyword.operator', foreground: 'b3e8b4' },
    { token: 'storage.type.function.arrow', foreground: 'b3e8b4' },
    { token: 'variable.css', foreground: '7AD9FB' },
    { token: 'source.css', foreground: 'CDF861' },
    { token: 'source.css meta.selector.css', foreground: 'CDF861' },
    { token: 'source.type.property-name.css', foreground: 'ffffff' },
    { token: 'keyword.css', foreground: lightTheme.colors.primary },
    { token: 'constant.numeric.css', foreground: lightTheme.colors.primary },
    { token: 'constant.other.color.css', foreground: lightTheme.colors.primary },
    { token: 'punctuation.section', foreground: '86897A' },
    { token: 'punctuation.separator', foreground: '86897A' },
    { token: 'punctuation.definition.entity.css', foreground: '86897A' },
    { token: 'punctuation.terminator.rule.css', foreground: 'E5E5E5' },
    { token: 'punctuation.definition.string.css', foreground: 'CABEFF' },
    { token: 'keyword.other.unit.css', foreground: 'CABEFF' },
    { token: 'string.css', foreground: 'CABEFF' },
    { token: 'support.type.property-name', foreground: 'ffffff' },
    { token: 'string.html', foreground: 'CDF861' },
    { token: 'punctuation.definition.tag', foreground: '86897A' },
    { token: 'entity.other.attribute-name', foreground: 'CABEFF' },
    { token: 'entity.name.tag', foreground: lightTheme.colors.primary },
    { token: 'entity.name.tag.wildcard', foreground: 'CDF861' },
    { token: 'markup.markdown', foreground: 'ffffff' },
    { token: 'markup.heading.markdown', foreground: 'b3e8b4' },
    { token: 'punctuation.definition.bold.markdown', foreground: 'b3e8b4' },
    {
      token: 'punctuation.definition.link.description',
      foreground: 'b3e8b4',
    },
    { token: 'punctuation.definition.raw.markdown', foreground: 'b3e8b4' },
    { token: 'meta.paragraph.markdown', foreground: 'E5E5E5' },
    { token: 'text.html.markdown meta.attribute', foreground: 'CABEFF' },
    { token: 'string.other', foreground: 'ffffff' },
    { token: 'string.other.link', foreground: 'ffffff' },
    { token: 'punctuation.definition.markdown', foreground: 'b3e8b4' },
    { token: 'punctuation.definition.string', foreground: 'b3e8b4' },
    {
      token: 'punctuation.definition.string.begin.shell',
      foreground: 'b3e8b4',
    },
    { token: 'markup.underline.link', foreground: 'ffffff' },
    { token: 'markup.inline.raw', foreground: '86897A' },
  ],
};

const takaroDarkTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,

  colors: {
    background: darkTheme.colors.background,
    foreground: darkTheme.colors.text,
    // focusBorder: 'AD9CFF',
    'selection.background': darkTheme.colors.primary,
    'selection.foreground': darkTheme.colors.text,

    // 'scrollbar.shadow': '0000007e',
    // 'input.background': '0F0E0E',
    // 'input.foreground': '999',
    // 'button.background': 'edffa5',
    // 'button.foreground': '151515',
    // 'button.hoverBackground': 'dcff50',
    // 'textLink.foreground': 'e5e5e5',
    // 'button.secondaryForeground': 'c5c5c5',
    // 'button.secondaryBacground': '2a2a2a',
    // 'button.secondaryHoverBackground': '373737',
    //
    // 'activityBar.foreground': 'dedede',
    // 'activityBar.background': '000',
    // 'activityBar.inactiveForeground': '999',
    // 'activityBarBadge.foreground': '000',
    // 'activityBarBadge.background': 'edffa5',
    // 'activityBar.border': '000',
    // 'actibityBar.activeBackground': '151515',
    //
    // 'sideBar.background': '000',
    // 'sideBar.foreground': '999',
    // 'sideBarSectionHeader.background': '151515',
    // 'sideBarSectionHeader.border': '00000000',
    // 'sideBarSectionHeader.foreground': 'e5e5e5',
    // 'sideBarTitle.foreground': 'e5e5e5',
    // 'sideBar.border': '00000000',
    // 'list.dropBackground': '151515',
    // 'list.focusForeground': '808080',
    // 'list.focusBackground': 'e5e5e51a',
    // 'list.highlightForeground': 'e5e5e5',
    'list.activeSelectionBackground': darkTheme.colors.backgroundAlt,
    'list.activeSelectionForeground': darkTheme.colors.text,
    //
    // 'statusBar.background': '000',
    // 'statusBar.foreground': '808080',
    // 'statusBar.border': '00000000',
    // 'statusBar.debuggingBackground': '563300',
    // 'statusBar.debuggingForeground': '999',
    // 'statusBar.noFolderBackground': '5d3fe0',
    // 'statusBar.noFolderForeground': 'e5e5e5',
    // 'statusBarItem.remoteBackground': 'cef144',
    // 'statusBarItem.remoteForeground': '151515',
    //
    // 'tab.activeBackground': '151515',
    // 'tab.activeForeground': 'e5e5e5',
    // 'tab.inactiveBackground': '000',
    // 'tab.inactiveForeground': '999',
    // 'tab.hoverBackground': 'E5E5E51A',
    // 'tab.border': '151515',
    //
    // 'titleBar.activeBackground': '000',
    // 'titleBar.activeForeground': '808080',
    // 'titleBar.border': '00000000',
    // 'titleBar.inactiveBackground': '000',
    //
    'menu.foreground': darkTheme.colors.text,
    'menu.background': darkTheme.colors.backgroundAlt,
    // 'menubar.selectionForeground': 'c5c5c5',
    // 'menubar.selectionBackground': 'e5e5e51a',
    'menu.selectionForeground': darkTheme.colors.text,
    'menu.selectionBackground': darkTheme.colors.backgroundAlt,
    'menu.selectionBorder': darkTheme.colors.primary,
    'menu.border': darkTheme.colors.backgroundAccent,
    //
    'editor.background': darkTheme.colors.background,
    // 'editorLineNumber.foreground': '858585',
    // 'editorLineNumber.activeForeground': 'c6c6c6',
    //
    'editor.lineHighlightBackground': darkTheme.colors.backgroundAlt,
    'editor.lineHighlightBorder': darkTheme.colors.backgroundAlt,
    //
    // 'breadcrumb.background': '151515',
    // 'breadcrumb.foreground': '999',
    // 'breadcrumb.focusForeground': 'e5e5e5',
    // 'editorGroupHeader.border': '00000000',
    // 'editorGroupHeader.tabsBackground': '000',
    //
    // 'scrollbarSlider.background': '79797966',
    // 'scrollbarSlider.hoverBackground': '646464b3',
    // 'scrollbarSlider.activeBackground': 'bfbfbf66',
    //
    // 'widget.shadow': '0000005c',
    'editorWidget.foreground': darkTheme.colors.text,
    'editorWidget.background': darkTheme.colors.backgroundAlt,
    'editorWidget.border': darkTheme.colors.backgroundAccent,

    'editor.selectionBackground': darkTheme.colors.primary,
    'editor.selectionForeground': darkTheme.colors.text,

    // 'pickerGroup.border': '3f3f46',
    // 'pickerGroup.foreground': '3794ff',
    // 'editorWidget.resizeBorder': '5f5f5f',
    // 'debugToolBar.background': '333',
    // 'debugToolBar.border': '474747',
    //
    // errorForeground: 'f48771',
    // warningForeground: 'F7CC66',
    // 'editorError.foreground': 'f48771',
    // 'list.errorForeground': 'f48771',
    // 'list.warningForeground': 'F7CC66',
    // 'editorWarning.foreground': 'F7CC66',
    //
    // 'gitDecoration.deletedResourceForeground': 'C54444',
    // 'gitDecoration.untrackedResourceForeground': '9FE7A0',
    // 'gitDecoration.conflictingResourceForeground': 'ED6C6C',
    // 'gitDecoration.ignoredResourceForeground': '585858',
    // 'gitDecoration.modifiedResourceForeground': 'DD763C',
  },

  rules: [
    { token: 'string', foreground: 'BFD084' },
    {
      token: 'punctuation.definition.string',
      foreground: darkTheme.colors.primary,
    },
    {
      token: 'constant.character.escape',
      foreground: darkTheme.colors.primary,
    },
    {
      token: 'text.html constant.character.entity.named',
      foreground: darkTheme.colors.primary,
    },
    { token: 'text.html.derivative', foreground: 'E5E5E5' },
    {
      token: 'punctuation.definition.entity.html',
      foreground: darkTheme.colors.primary,
    },
    { token: 'template.expression.begin', foreground: '7AD9FB' },
    { token: 'template.expression.end', foreground: '7AD9FB' },
    {
      token: 'punctuation.definition.template-expression.begin',
      foreground: '7AD9FB',
    },
    {
      token: 'punctuation.definition.template-expression.end',
      foreground: '7AD9FB',
    },

    { token: 'variable', foreground: 'ff0000' },
    { token: 'variable.other', foreground: 'ffffff' },
    { token: 'variable.parameter', foreground: 'ffffff' },
    { token: 'variable.language', foreground: '00ff00' },

    { token: 'constant', foreground: '7AD9FB' },
    { token: 'keyword', foreground: darkTheme.colors.primary },
    { token: 'modifier', foreground: darkTheme.colors.primary },
    { token: 'storage', foreground: darkTheme.colors.primary },
    { token: 'punctuation.definition.block', foreground: '86897A' },
    { token: 'punctuation.definition.parameters', foreground: '86897A' },
    { token: 'punctuation.accessor', foreground: '86897A' },
    { token: 'source.groovy.embedded', foreground: 'E5E5E5' },
    { token: 'comment', foreground: '6f6f6f' },
    { token: 'docblock', foreground: '6f6f6f' },

    { token: 'meta.function-call', foreground: 'CDF861' },
    { token: 'meta.brace.round', foreground: '86897A' },
    { token: 'meta.jsx.children', foreground: 'E5E5E5' },
    { token: 'meta.embedded', foreground: 'E5E5E5' },
    { token: 'meta.template.expression', foreground: 'E5E5E5' },
    { token: 'meta.type.annotation', foreground: darkTheme.colors.primary },
    { token: 'meta.type.annotation entity.name.type', foreground: 'CABEFF' },
    { token: 'meta.definition.variable', foreground: '00ff00' },

    { token: 'entity.name.type.class', foreground: 'ffffff' },
    { token: 'entity.name.type.module', foreground: 'CABEFF' },
    { token: 'entity.name.function', foreground: 'ff0000' },
    { token: 'entity.name.tag.css', foreground: 'CDF861' },
    { token: 'entity.name.section', foreground: 'ffffff' },

    { token: 'entity.other.attribute-name', foreground: 'CDF861' },
    { token: 'entity.other.attribute-name.id', foreground: 'CDF861' },
    { token: 'entity.other.attribute-name.class', foreground: 'CDF861' },
    { token: 'entity.other.inherited-class', foreground: darkTheme.colors.primary },

    { token: 'variable.object.property', foreground: 'ffffff' },
    { token: 'modifier', foreground: darkTheme.colors.primary },
    { token: 'variable.language.this', foreground: darkTheme.colors.primary },
    { token: 'support.type.object', foreground: darkTheme.colors.primary },
    { token: 'support.module', foreground: '7AD9FB', fontStyle: 'italic' },
    { token: 'support.node', foreground: '7AD9FB', fontStyle: 'italic' },
    { token: 'support.type.ts', foreground: '7AD9FB' },
    { token: 'support.function.css', foreground: darkTheme.colors.primary },
    { token: 'support.constant.css', foreground: darkTheme.colors.primary },
    { token: 'keyword.operator', foreground: 'b3e8b4' },
    { token: 'storage.type.function.arrow', foreground: 'b3e8b4' },
    { token: 'variable.css', foreground: '7AD9FB' },
    { token: 'source.css', foreground: 'CDF861' },
    { token: 'source.css meta.selector.css', foreground: 'CDF861' },
    { token: 'source.type.property-name.css', foreground: 'ffffff' },
    { token: 'keyword.css', foreground: darkTheme.colors.primary },
    { token: 'constant.numeric.css', foreground: darkTheme.colors.primary },
    { token: 'constant.other.color.css', foreground: darkTheme.colors.primary },
    { token: 'punctuation.section', foreground: '86897A' },
    { token: 'punctuation.separator', foreground: '86897A' },
    { token: 'punctuation.definition.entity.css', foreground: '86897A' },
    { token: 'punctuation.terminator.rule.css', foreground: 'E5E5E5' },
    { token: 'punctuation.definition.string.css', foreground: 'CABEFF' },
    { token: 'keyword.other.unit.css', foreground: 'CABEFF' },
    { token: 'string.css', foreground: 'CABEFF' },
    { token: 'support.type.property-name', foreground: 'ffffff' },
    { token: 'string.html', foreground: 'CDF861' },
    { token: 'punctuation.definition.tag', foreground: '86897A' },
    { token: 'entity.other.attribute-name', foreground: 'CABEFF' },
    { token: 'entity.name.tag', foreground: darkTheme.colors.primary },
    { token: 'entity.name.tag.wildcard', foreground: 'CDF861' },
    { token: 'markup.markdown', foreground: 'ffffff' },
    { token: 'markup.heading.markdown', foreground: 'b3e8b4' },
    { token: 'punctuation.definition.bold.markdown', foreground: 'b3e8b4' },
    {
      token: 'punctuation.definition.link.description',
      foreground: 'b3e8b4',
    },
    { token: 'punctuation.definition.raw.markdown', foreground: 'b3e8b4' },
    { token: 'meta.paragraph.markdown', foreground: 'E5E5E5' },
    { token: 'text.html.markdown meta.attribute', foreground: 'CABEFF' },
    { token: 'string.other', foreground: 'ffffff' },
    { token: 'string.other.link', foreground: 'ffffff' },
    { token: 'punctuation.definition.markdown', foreground: 'b3e8b4' },
    { token: 'punctuation.definition.string', foreground: 'b3e8b4' },
    {
      token: 'punctuation.definition.string.begin.shell',
      foreground: 'b3e8b4',
    },
    { token: 'markup.underline.link', foreground: 'ffffff' },
    { token: 'markup.inline.raw', foreground: '86897A' },
  ],
};
