import { IScenarioEvent } from '../lib/gameserver/scenario.js';

export const Basic: IScenarioEvent[] = [
  { time: 0, event: 'player-connected', data: { player: '1' } },
  { time: 473, event: 'player-connected', data: { player: '2' } },
  { time: 1555, event: 'player-connected', data: { player: '3' } },
  { time: 1955, event: 'chat-message', data: { player: '2', msg: '/ping', channel: 'global' } },
  { time: 2092, event: 'chat-message', data: { player: '3', msg: '/ping', channel: 'global' } },
  { time: 2948, event: 'player-disconnected', data: { player: '1' } },
  { time: 3112, event: 'chat-message', data: { player: '2', msg: '/settp home', channel: 'global' } },
  { time: 3422, event: 'player-connected', data: { player: '4' } },
  { time: 4061, event: 'chat-message', data: { player: '3', msg: '/teleport home', channel: 'global' } },
  { time: 4406, event: 'chat-message', data: { player: '4', msg: '/ping', channel: 'global' } },
  { time: 4873, event: 'chat-message', data: { player: '2', msg: '/ping', channel: 'global' } },
  { time: 4892, event: 'chat-message', data: { player: '1', msg: '/ping', channel: 'global' } },
  { time: 5137, event: 'chat-message', data: { player: '4', msg: '/settp shop', channel: 'global' } },
  { time: 5268, event: 'player-disconnected', data: { player: '2' } },
  { time: 5665, event: 'chat-message', data: { player: '3', msg: '/ping', channel: 'global' } },
  { time: 5809, event: 'player-connected', data: { player: '5' } },
  { time: 6624, event: 'player-connected', data: { player: '2' } },
  { time: 7273, event: 'chat-message', data: { player: '4', msg: '/teleport shop', channel: 'global' } },
  { time: 7477, event: 'chat-message', data: { player: '2', msg: '/ping', channel: 'global' } },
  { time: 7489, event: 'chat-message', data: { player: '1', msg: '/ping', channel: 'global' } },
  { time: 8027, event: 'chat-message', data: { player: '4', msg: '/settp farm', channel: 'global' } },
  { time: 8427, event: 'chat-message', data: { player: '2', msg: '/settp home', channel: 'global' } },
  { time: 8861, event: 'chat-message', data: { player: '3', msg: '/teleport farm', channel: 'global' } },
  { time: 9473, event: 'chat-message', data: { player: '2', msg: '/teleport home', channel: 'global' } },
  { time: 9815, event: 'player-disconnected', data: { player: '3' } },
  { time: 10102, event: 'chat-message', data: { player: '5', msg: '/ping', channel: 'global' } },
  { time: 10808, event: 'player-connected', data: { player: '5' } },
  { time: 11231, event: 'chat-message', data: { player: '4', msg: '/ping', channel: 'global' } },
  { time: 11564, event: 'chat-message', data: { player: '1', msg: '/settp farm', channel: 'global' } },
  { time: 12022, event: 'chat-message', data: { player: '5', msg: '/ping', channel: 'global' } },
  { time: 12325, event: 'chat-message', data: { player: '2', msg: '/ping', channel: 'global' } },
  { time: 12727, event: 'chat-message', data: { player: '5', msg: '/settp shop', channel: 'global' } },
  { time: 12875, event: 'chat-message', data: { player: '5', msg: '/ping', channel: 'global' } },
  { time: 13142, event: 'player-disconnected', data: { player: '4' } },
  { time: 13153, event: 'player-disconnected', data: { player: '5' } },
  { time: 14611, event: 'chat-message', data: { msg: '/ping', player: '2', channel: 'global' } },
  { time: 15416, event: 'chat-message', data: { msg: '/ping', player: '3', channel: 'global' } },
  { time: 16042, event: 'chat-message', data: { msg: 'how is everyone doing?', player: '4', channel: 'global' } },
  { time: 16669, event: 'player-disconnected', data: { player: '2' } },
  { time: 17220, event: 'player-connected', data: { player: '5' } },
  {
    time: 17905,
    event: 'chat-message',
    data: { msg: "I'm heading to the teleport named 'spawn'", player: '1', channel: 'global' },
  },
  { time: 18816, event: 'chat-message', data: { msg: '/teleport spawn', player: '1', channel: 'global' } },
  {
    time: 19258,
    event: 'chat-message',
    data: { msg: "I'm heading to the teleport named 'home'", player: '5', channel: 'global' },
  },
  { time: 19812, event: 'chat-message', data: { msg: '/settp home', player: '5', channel: 'global' } },
  { time: 20236, event: 'chat-message', data: { msg: '/ping', player: '1', channel: 'global' } },
  { time: 21213, event: 'chat-message', data: { msg: 'anyone want to team up?', player: '4', channel: 'global' } },
  { time: 22337, event: 'chat-message', data: { msg: '/ping', player: '1', channel: 'global' } },
  { time: 23167, event: 'chat-message', data: { msg: "I'll join your team, 4", player: '2', channel: 'global' } },
  {
    time: 23942,
    event: 'chat-message',
    data: { msg: 'Great, we could use some help', player: '4', channel: 'global' },
  },
  { time: 24660, event: 'player-connected', data: { player: '5' } },
  {
    time: 25414,
    event: 'chat-message',
    data: { msg: 'Hey 5, want to join our team?', player: '4', channel: 'global' },
  },
  { time: 25962, event: 'chat-message', data: { msg: '/ping', player: '1', channel: 'global' } },
  { time: 26472, event: 'chat-message', data: { msg: "I'm in! where are you guys?", player: '5', channel: 'global' } },
  {
    time: 27293,
    event: 'chat-message',
    data: { msg: "We're at the teleport named 'base', 5", player: '2', channel: 'global' },
  },
  { time: 28041, event: 'chat-message', data: { msg: '/teleport base', player: '5', channel: 'global' } },
];
