name: Auto-update
# Auto-update only listens to `push` events.
# If a pull request is already outdated when enabling auto-merge, manually click on the "Update branch" button a first time to avoid having to wait for another commit to land on the base branch for the pull request to be updated.
on: push
# If pull requests are always based on the same branches, only triggering the workflow when these branches receive new commits will minimize the workflow execution.
#on:
#  push:
#    branches:
#      - main

jobs:
  Auto:
    name: Auto-update
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.TAKARO_CI_APP_ID }}

          # Optional.
          # github_api_url: https://api.example.com

          # Optional.
          # installation_id: 1337

          # Optional.
          # Using a YAML multiline string to avoid escaping the JSON quotes.
          # permissions: >-
          #   {"members": "read"}

          private_key: ${{ secrets.TAKARO_CI_APP_PRIV_KEY }}

          # Optional.
          # repository: owner/repo

      - uses: tibdex/auto-update@v2
        with:
          github_token: ${{ steps.generate_token.outputs.token }}      